### ISSUE TITLE
RFC: core scope (MVP)

### ISSUE THREAD

**Issue by mdjastrzebski** [callstack/ts-regex-builder#22]
In order to prepare MVP version we need to implement core regex features so that the package is useful for typical use cases.

## Core scope
- [x] Features
  - [x] `buildRegex`, `buildPattern` top-level APIs
    - [x] RegExp `flags`
  - [x] quantifiers
    - [x] base: `one`, `oneOrMore`, `zeroOrMore`, `optionally`
    - [x] `repeat`
  - [x] `choiceOf` alternative
  - [x] character classes
    - [x] base classes: `any` (`.`), `digit` (`\d`), `word` (`\w`), `whitespace` (`\s`)
    - [x] `anyOf` class
    - [x] `characterClass` helper
    - [x] `characterRange` class
    - [x] `inverted` modifier (`^`)
  - [x] captures:
    - [x] `capture`
  - [x] anchors
    - [x] base: `startOfLine` (`^`), `endOfLine` (`$`)
- [x] Documentation
  - [x] Getting started guide
  - [x] API reference
  - [x] 5 meaningful examples
- [x] CI/CD
- [x] Publish to NPM

## Things after MVP
- [ ] `Lookahead` / `NegativeLookahead`
- [ ] More exotic character classes
- [ ] More exotic anchors
- [ ] `Local` capture (not sure if relevant)
- [ ] Character class operations: `union`, `intersection`, etc  (not sure if relevant)
- [ ] Other anchors
  - [ ] `wordBoundary` (`\b`)
  - [ ]  inverted anchors
- [ ] Advanced captures (not sure if relevant)
  - [ ]  `transform` option
  - [ ] `tryCapture` with `transform`
  - [ ] `reference` (`as`)

**Comment by jaworek** [comment]
I'll work on `startOfLine` (^), `endOfLine` ($) anchors
