### ISSUE TITLE
[Bug]test-utils/ts-match-string doesn't work with trailing lookaheads.

### ISSUE THREAD

**Issue by PaulJPhilp** [callstack/ts-regex-builder#81]
**Describe the bug**
A regular expression that ends with a lookahead not supported by ts-match-string.

**To Reproduce**
Steps to reproduce the behaviour:

Building a regex to match the Scheme ("ftp:") of a URL.
Use a positive lookahead to match the trailing ':'.

1. Create a regex that has a trailing positive lookahead:
        const urlScheme = buildRegExp(
            [choiceOf(schemePlural, schemeSingular), lookahead(':')],
         );
2. Create tests using the character from the positive lookahead as the final character.
        1) expect(urlSchemeValidator).toMatchString('ftp:');
        2) expect("ftp:").toMatch(urlSchemeValidator);
        3) expect('ftp').toMatch(urlSchemeValidator);  // for completeness
        4) expect(urlSchemeValidator).toMatchString('ftp');  // for completeness

**Expected behaviour**
Test 1) and 2) should pass and 3) and 4) should not pass.
Instead, all 4 tests fail.

**Screenshots**
![image](https://github.com/callstack/ts-regex-builder/assets/138239846/7b84474d-8c03-4ec0-aa02-eeef5c7660d3)

**Package version**
`ts-regex-builder: `

**Additional context**

I have a solution to propose in an upcoming PR.

**Comment by mdjastrzebski** [comment]
@PaulJPhilp thank you for reporting it. Is it a matter of escaping `:` in lookahead construct (`(?=:)`)? Are there any other characters that should also be escaped in such case.?

**Comment by PaulJPhilp** [comment]
No.  It is just using the library.  I understand the issue better now.

The problem is in the testing utility: **ToMatchString()**.  I came to think the issue is missing functionality:

I created a a regex builder (urlSheme) to recognize a URL scheme e.g. (http:).  I used a positive lookahead to match the ':'.
Now I want to test it.  I can:

1. expect(urlScheme).toMatchString("http") - the result is false because 'http' does have the ':' character to match the lookahead.
2. expect(urlScheme).toMatchString("http:") - the result is false because because there is not character after the ':'.  It's a subtle issue. In the end, I had to manually walk through the state machine to understand what is happening.  The positive lookahead matches the ':' but does not consume it.  So there is one more character left but the pattern is exhausted so the match fails.

Conceptually, you need a toMatchSubstring('http', 'http:') which matches because 'http' is a substring of 'http:'.

I tried a few APIs and settled on:
`interface MatchTypeOptions {
  exactString: boolean;
  substring?: string;
}

export function toMatchString(
  this: jest.MatcherContext,
  received: RegExp | RegexSequence,
  expected: string,
  matchType?: MatchTypeOptions,
)` in my PR.

I changed a few existing tests (currency, filename, suffixes) to use the new API.  I think that those test were getting the correct result for the wrong reason.  Here's how it looks:

```
 expect(currencyRegex).toMatchString('$10', { exactString: false, substring: '10' });
 expect(filenameRegex).toMatchString('index.ts', { exactString: false });
 expect(regex).toMatchString('democracy', { exactString: false });
```

This is the biggest reason my PR got so large.  Take a look.

I'm not married to the API, so feel free to suggest an alternative.

**Comment by mdjastrzebski** [comment]
As far as I understand the issue is in that you use a lookahead + immediate end of string, but without any other pattern that would consume the ":" character.

This should be easy to fix by just swapping `lookahead(":")` with `":"`. Otherwise you pattern requires that both happen an the same time: 
* there is a `:` char right after `ftp`
* there is end of string right after `ftp`

By using plain `":"`, you reconcile these two by matching the colon as well as consuming it before matching end of string.

**Comment by mdjastrzebski** [comment]
`toMatchString` is just an internal testing helper, it's not part of our public API. It's basically a wrapper around `String.match` method. 

Could you verify the issues you are observing using plain RegExp (`String`) methods like `RegExp.test`, `RegExp.exec` or `String.match`?

**Comment by PaulJPhilp** [comment]
Yes, I understand what toMatchString() is.  It wasn't always clear that the
issue was in the testing helper.  Blaming the test tools first is not a
great idea.

I've used regex testing tools (https://regex101.com/) and visualizers (
https://www.debuggex.com/).

Here's a tester with a simple regex that demonstrates the issue.

const regex = /[a-zA-z]{2,4}(?=:)/

const result1 = "http".match(regex)
const result2 = "http:".match(regex)
const result3 = regex.test("http")
const result4 = regex.test("http:")
const result5 = regex.exec("http")
const result6 = regex.exec("http:")

console.log("RESULT 1\n", result1)
console.log("RESULT 2\n", result2)
console.log("RESULT 3\n", result3)
console.log("RESULT 4\n", result4)
console.log("RESULT 5\n", result5)
console.log("RESULT 6\n", result6)

Here are the results.  Notice that 'http:' matches the 'http' substring of
'http:'.

***@***.*** ts-regex-builder % bun issue.ts
RESULT 1
 null
RESULT 2
 [ "http" ]
RESULT 3
 false
RESULT 4
 true
RESULT 5
 null
RESULT 6
 [ "http" ]

**Comment by mdjastrzebski** [comment]
Not sure how relevant is it, but your first example used `startOfString` `endOfString` to wrap the pattern, but your last example does not use it (nor `^` & `$`).

**Comment by PaulJPhilp** [comment]
Yes.  The first 2 are the 'finder' and 'validator' pattern.  They can use
the start and end of string characters.
The reusable 'urlScheme' cannot use them.

**Comment by PaulJPhilp** [comment]
I have an idea.  In my most recent PR, I have a proposed solution to this
issue.

I'd be happy to pull it out of that PR and create a PR for just that
solution.  That would give
you a chance to see it and play with it.  The current API is my 3rd
version, so I'm sure that
there is a 4th that would improve it.

**Comment by mdjastrzebski** [comment]
Please do so, it will be easier to focus that issue, as for now I don't feel like I understand it exactly.

**Comment by PaulJPhilp** [comment]
I have submitted the PR with only the changes in the ts-match-string API,
and the tests that were impacted by the issue or the fix.

**Comment by PaulJPhilp** [comment]
OK, after dealing with this issue for a couple of weeks now, I think I
finally understand it well enough to explain
it simply.  It has to do with non-capturing operations in patterns.

Example:  expect(/[a-z]{2,6}(?=:)/).toMatchString("http:").

1) The pattern has a non-capture operation `(?=:)`
2) The test string has that character (toMatchString("http:"))
3) The non-capturing op matches the character (:).
4) The character is not-captured.
5) The ':' is left in the test string.
6) The regex state machine has finished.

Therefore
1) The full string match fails.
2) In exec(), the substring "http" is matched, so the exec() passes.

In the general case, where the non-capture character is in the middle of
the test string,
the issue is that when the non-capture character is matched, that character
is left in the
test string but the state machine has moved on to the next character.  In
this case, there
will be too many characters remaining in the test string.  The state
machine will finish
before all the characters in the test string have been exhausted.  So, only
a substring
of the test string can be possible matches.

*Conclusion*

toMatchString(testString) cannot be used to test patterns with
non-capturing ops
in the pattern being matched against.

**Comment by mdjastrzebski** [comment]
Let's gather the findings so far:

* the pattern `/[a-z]{2,4}(?=:)/` will match "http:"
* but pattern `/^[a-z]{2,4}(?=:)$/ ` will not match "http:"
* `toMatchString()` test utility is a simple wrapper over `String.match`, and the behavior you observed with `expect(regex)toMatchString("http:")` would be also observed with `"http:".match(/^[a-z]{2,4}(?=:)$/)
* [lookaheads](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Lookahead_assertion) `(?=...)` do not consume regex characters. As the name suggest they "look ahead"
* using `$` (end of string) would only work if the `:` got consumed, which we can get by replacing lookahead with regular character match `/^[a-z]{2,4}:$/`

As far as I understand your issue,  and I am not sure whether I understand it correctly, you would like to have regex with both lookahead for `:` character (for nesting regex expressions) and be able to use end of string anchor (for validation).

If so, the I think this is not achievable using one regex pattern. There would have to be two:
- validation (consuming `:`, end of string assertion) `/^[a-z]{2,4}:$/`
- nesting (not consuming `:`, no end of string assertion) `/[a-z]{2,4}(?=:)/`

Let me know if I've got that right or did I miss something.

**Comment by PaulJPhilp** [comment]
Nope.

The issue is that you can't use toMatchString() as it is to test a pattern
with lookaheads in them.  At all.

That's the only issue I am talking about.
